spring.application.name=company-service

#DATABASE
spring.datasource.url=jdbc:postgresql://postgres:5432/company_service_db
spring.datasource.username=root
spring.datasource.password=peanutbutter
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

#ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true

management.info.env.enabled=true

info.app.name=CompanyService
info.app.description=service for job-app


#EUREKA
eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#ZIPKIN
management.tracing.sampling.probability=1

#review.service.uri=http://REVIEW-SERVICE:8084/reviews
server.port=8083
