spring:
  application:
    name: job-service

  #DATABASE
  datasource:
    url: jdbc:postgresql://postgres:5432/job_service_db
    username: root
    password: peanutbutter

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: create-drop

#ACTUATOR
management:

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true


  health:
    circuitbreakers:
      enabled: true

  info:
    - env.enabled: true

  ##ZIPKIN
  tracing:
    - sampling.probability: 1

info:
  app:
    name: JobService
    description: service for job-app

eureka:
  client:
    serviceUrl.defaultZone: http://serviceregistry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

resilience4j.retry:
  instances:
    retryGet:
      maxAttempts: 5
      waitDuration: 2s


resilience4j.ratelimiter:
  instances:
    createLimiter:
      timeoutDuration: 0
      limitRefreshPeriod: 5000ms
      limitForPeriod: 1
    deleteLimiter:
      timeoutDuration: 0
      limitRefreshPeriod: 5000ms
      limitForPeriod: 1
    updateLimiter:
      timeoutDuration: 0
      limitRefreshPeriod: 5000ms
      limitForPeriod: 1


server:
  port: 8082
